In this step, we’re going to make a simple change to our
`+Containerfile+` and re-build our image.

== Modifying a Containerfile
Right now Apache serves it's default test page, let's add a new 
index.html. A new index has been prepared in the `app` directory, let's 
see what the new page should look like.

[source,bash,run]
----
cat app/index.html
----

Open the `Containerfile` in an editor

[source,bash,run]
----
vi Containerfile
----

After the line `+EXPOSE 80+` add the following command:
[source,dockerfile]
----
COPY app/index.html /var/www/html
----

Now we can re-build our image.

[source,bash,run]
----
podman build -t my-container .
----

This should re-build our container, but you’ll notice that it does not
go through the installation of httpd. That’s because our change happened
after that command. So podman doesn’t re-create those layers, it picks
up at the first different command.

Now, we can run a container from our image.

First, we should still have a running container from the last exercise.
You can stop it, and remove it with:

[source,bash,run]
----
podman stop my-httpd && podman rm my-httpd
----

If our goal is to replace the old container with a new container running
the new deployment of our app, we’ll have to stop our old container. We
do not necessarily have to remove it though, we do here because we are
re-using the same container name. If instead we wanted to run the
container with a new name, we could have stopped `+my-httpd+` and then
started a new container with a new name. If we didn’t stop the old
container, we would not be able to start the new container on port 8080.

[source,bash,run]
----
podman run -d -p 8080:80 --name my-httpd my-container
----

With the new container running, we can test it with curl.

[source,bash,run]
----
curl http://127.0.0.1:8080
----

How, instead of the stock "`It Worked`" apache page, you should get the
contents of the index.html we copied in.

In the next step, we’re going to show you another way that you might run
services inside of your container.
