== Running containers with init

Some container base images, offer the ability to start services using a
lightweight init system, rather than calling them directly in the
foreground. The container community usually frowns upon running service
this way, but some services were simply not designed to run without
being controlled by an init system. And running them in the foreground
could lead to data corruption if the foreground process does not exit
properly when the container exits. If you would like to run a container
using init, this might be a helpful example for you.

First, let’s Switch back over to the link:tab-1[button
label="`Containerfile`" background="`#ee0000`" color="`#c7c7c7`"] tab,
and open up the `+Containerfile+`.

The RHEL UBI base image that we’ve been using, has an alternate build
that supports a stripped down systemd init. You can use it simply by
following a few basic steps. First we need to change the `+FROM+` line
to:

....
FROM registry.access.redhat.com/ubi9/ubi-init
....

Now, we also need to enable the httpd service within systemd. So,
somewhere after httpd is installed, but before the `+CMD+` you should
add the following:

....
RUN systemctl enable httpd
....

In our example we add this as the last line before `+CMD+`.

The last change we need to make is the `+CMD+` itself. Change `+CMD+` to
:

....
CMD ["/sbin/init"]
....

Your `+Containerfile+` should now look like this:

Switch back to the link:tab-0[button label="`Terminal`"
background="`#ee0000`" color="`#c7c7c7`"] tab, so we can continue with
the container image build.

Now let’s build our new container image. But maybe we’re building this
as an alternative to the standard `+my-container+`, or perhaps we’re
testing this and do not want to replace `+my-container+`, so let’s give
this build a descriptive tag.

[source,bash,run]
----
cd ~/my-container
podman build -t my-container:init .
----

This should build us a new version of the image, starting from scratch,
based on the new base image.

[source,bash,run]
----
podman image list
----

Notice that there are now two images named `+localhost/my-container+`,
but they have different tags, init, and latest. Let’s run a new
container with the new image. Again, we’ll need to be sure that our old
container is stopped first.

[source,bash,run]
----
podman stop my-httpd
podman run -d -p 80:80 --name my-httpd-init my-container:init
----

Now, you should once again be able to connect to your container with
curl.

[source,bash,run]
----
curl http://127.0.0.1
----
