== Running containers with init

Some container base images, offer the ability to start services using a
lightweight init system, rather than calling them directly in the
foreground. The container community usually frowns upon running service
this way, but some services were simply not designed to run without
being controlled by an init system. And running them in the foreground
could lead to data corruption if the foreground process does not exit
properly when the container exits. If you would like to run a container
using init, this might be a helpful example for you.

The RHEL UBI base image that we’ve been using has an alternate build
that supports a stripped down `systemd`. You can use it simply by
modifying a few lines in the Containerfile.

[source,bash,run]
----
vi Containerfile
----

First we need to change the `+FROM+` line
to:

....
FROM registry.access.redhat.com/ubi10/ubi-init
....

Now, we also need to enable the httpd service within systemd. So,
somewhere after httpd is installed, but before the `+CMD+` you should
add the following:

....
RUN systemctl enable httpd
....

In our example we add this as the last line before `+CMD+`.

The last change we need to make is the `+CMD+` itself. 
Change `+CMD+` to:

....
CMD ["/sbin/init"]
....

Your `+Containerfile+` should now look like this:
[source,dockerfile]
----
FROM registry.access.redhat.com/ubi10/ubi-init # <1>
RUN dnf -y install httpd

EXPOSE 80

RUN systemctl enable httpd # <2>
CMD ["/sbin/init"] # <3>
----
<1> Systemd enabled UBI image
<2> Set httpd to start at runtime
<3> Change start command to call systemd instead of httpd

Now let’s build our new container image. But maybe we’re building this
as an alternative to the standard `+my-container+`, or perhaps we’re
testing this and do not want to replace `+my-container+`, so let’s give
this build a descriptive tag.

[source,bash,run]
----
podman build -t my-container:init .
----

This should build us a new version of the image, starting from scratch,
based on the new base image.

[source,bash,run]
----
podman image list
----

Notice that there are now two images named `+localhost/my-container+`,
but they have different tags, init, and latest. Let’s run a new
container with the new image. 

[source,bash,run]
----
podman run -d -p 80:80 --name my-httpd-init my-container:init
----

Now, you should once again be able to connect to your container with
curl.

[source,bash,run]
----
curl http://127.0.0.1
----

If you didn't stop the earlier container, you may get an error since 
we're reusing the same exposed port. Be sure to stop the `my-httpd`
container and try the `podman run` command again.
